<?php

namespace ContainerD8EJQoF;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getJobControllerupdateService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.wS0Bpip.App\Controller\JobController::update()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.wS0Bpip.App\\Controller\\JobController::update()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'job' => ['privates', '.errored..service_locator.wS0Bpip.App\\Entity\\JobOffer', NULL, 'Cannot autowire service ".service_locator.wS0Bpip": it needs an instance of "App\\Entity\\JobOffer" but this type has been excluded because it\'s a Doctrine entity.'],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'aiEnrichmentService' => ['privates', 'App\\Service\\AiEnrichmentService', 'getAiEnrichmentServiceService', true],
        ], [
            'job' => 'App\\Entity\\JobOffer',
            'em' => '?',
            'aiEnrichmentService' => 'App\\Service\\AiEnrichmentService',
        ]))->withContext('App\\Controller\\JobController::update()', $container);
    }
}
