<?php

namespace ContainerD8EJQoF;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getStudentControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.0dP2eJy.App\Controller\StudentController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.0dP2eJy.App\\Controller\\StudentController::delete()'] = ($container->privates['.service_locator.0dP2eJy'] ?? $container->load('get_ServiceLocator_0dP2eJyService'))->withContext('App\\Controller\\StudentController::delete()', $container);
    }
}
