<?php

namespace ContainerD8EJQoF;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getStudentControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.cGQEWDw.App\Controller\StudentController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.cGQEWDw.App\\Controller\\StudentController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'repository' => ['privates', 'App\\Repository\\StudentRepository', 'getStudentRepositoryService', true],
        ], [
            'repository' => 'App\\Repository\\StudentRepository',
        ]))->withContext('App\\Controller\\StudentController::index()', $container);
    }
}
