<?php

namespace ContainerZLJy6dA;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_EPFmjIEService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.EPFmjIE' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.EPFmjIE'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'aiEnrichmentService' => ['privates', 'App\\Service\\AiEnrichmentService', 'getAiEnrichmentServiceService', true],
        ], [
            'aiEnrichmentService' => 'App\\Service\\AiEnrichmentService',
        ]);
    }
}
