<?php

namespace ContainerZLJy6dA;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAiControllerjobMatchService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.EPFmjIE.App\Controller\AiController::jobMatch()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.EPFmjIE.App\\Controller\\AiController::jobMatch()'] = ($container->privates['.service_locator.EPFmjIE'] ?? $container->load('get_ServiceLocator_EPFmjIEService'))->withContext('App\\Controller\\AiController::jobMatch()', $container);
    }
}
