<?php

namespace ContainerVMVgGxS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAiEnrichmentServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\AiEnrichmentService' shared autowired service.
     *
     * @return \App\Service\AiEnrichmentService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/AiEnrichmentService.php';

        return $container->privates['App\\Service\\AiEnrichmentService'] = new \App\Service\AiEnrichmentService(\dirname(__DIR__, 4));
    }
}
