<?php

namespace ContainerVMVgGxS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAiControllerprofileSummaryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.EPFmjIE.App\Controller\AiController::profileSummary()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.EPFmjIE.App\\Controller\\AiController::profileSummary()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'aiEnrichmentService' => ['privates', 'App\\Service\\AiEnrichmentService', 'getAiEnrichmentServiceService', true],
        ], [
            'aiEnrichmentService' => 'App\\Service\\AiEnrichmentService',
        ]))->withContext('App\\Controller\\AiController::profileSummary()', $container);
    }
}
