<?php

namespace ContainerVMVgGxS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCompanyControllerupdateService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.hSlFnVO.App\Controller\CompanyController::update()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.hSlFnVO.App\\Controller\\CompanyController::update()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'company' => ['privates', '.errored..service_locator.hSlFnVO.App\\Entity\\Company', NULL, 'Cannot autowire service ".service_locator.hSlFnVO": it needs an instance of "App\\Entity\\Company" but this type has been excluded because it\'s a Doctrine entity.'],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'company' => 'App\\Entity\\Company',
            'em' => '?',
        ]))->withContext('App\\Controller\\CompanyController::update()', $container);
    }
}
