<?php

namespace ContainerVMVgGxS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSchoolService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.mCngn_M.App\Entity\School' shared service.
     *
     * @return \App\Entity\School
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.mCngn_M": it needs an instance of "App\\Entity\\School" but this type has been excluded because it\'s a Doctrine entity.');
    }
}
