<?php

namespace Container9CGsSx8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_JGZ_SKnService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.jGZ.SKn' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.jGZ.SKn'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Controller\\CompanyController::index' => ['privates', '.service_locator.z0A7H.F.App\\Controller\\CompanyController::index()', 'getCompanyControllerindexService', true],
            'App\\Controller\\CompanyController::update' => ['privates', '.service_locator.hSlFnVO.App\\Controller\\CompanyController::update()', 'getCompanyControllerupdateService', true],
            'App\\Controller\\JobController::index' => ['privates', '.service_locator.z0A7H.F.App\\Controller\\JobController::index()', 'getJobControllerindexService', true],
            'App\\Controller\\JobController::update' => ['privates', '.service_locator.y.LjztN.App\\Controller\\JobController::update()', 'getJobControllerupdateService', true],
            'App\\Controller\\SchoolController::index' => ['privates', '.service_locator.z0A7H.F.App\\Controller\\SchoolController::index()', 'getSchoolControllerindexService', true],
            'App\\Controller\\SchoolController::update' => ['privates', '.service_locator.mCngn_M.App\\Controller\\SchoolController::update()', 'getSchoolControllerupdateService', true],
            'App\\Controller\\StudentController::index' => ['privates', '.service_locator.cGQEWDw.App\\Controller\\StudentController::index()', 'getStudentControllerindexService', true],
            'App\\Controller\\StudentController::create' => ['privates', '.service_locator.z0A7H.F.App\\Controller\\StudentController::create()', 'getStudentControllercreateService', true],
            'App\\Controller\\StudentController::update' => ['privates', '.service_locator.0dP2eJy.App\\Controller\\StudentController::update()', 'getStudentControllerupdateService', true],
            'App\\Controller\\StudentController::delete' => ['privates', '.service_locator.0dP2eJy.App\\Controller\\StudentController::delete()', 'getStudentControllerdeleteService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Controller\\CompanyController:index' => ['privates', '.service_locator.z0A7H.F.App\\Controller\\CompanyController::index()', 'getCompanyControllerindexService', true],
            'App\\Controller\\CompanyController:update' => ['privates', '.service_locator.hSlFnVO.App\\Controller\\CompanyController::update()', 'getCompanyControllerupdateService', true],
            'App\\Controller\\JobController:index' => ['privates', '.service_locator.z0A7H.F.App\\Controller\\JobController::index()', 'getJobControllerindexService', true],
            'App\\Controller\\JobController:update' => ['privates', '.service_locator.y.LjztN.App\\Controller\\JobController::update()', 'getJobControllerupdateService', true],
            'App\\Controller\\SchoolController:index' => ['privates', '.service_locator.z0A7H.F.App\\Controller\\SchoolController::index()', 'getSchoolControllerindexService', true],
            'App\\Controller\\SchoolController:update' => ['privates', '.service_locator.mCngn_M.App\\Controller\\SchoolController::update()', 'getSchoolControllerupdateService', true],
            'App\\Controller\\StudentController:index' => ['privates', '.service_locator.cGQEWDw.App\\Controller\\StudentController::index()', 'getStudentControllerindexService', true],
            'App\\Controller\\StudentController:create' => ['privates', '.service_locator.z0A7H.F.App\\Controller\\StudentController::create()', 'getStudentControllercreateService', true],
            'App\\Controller\\StudentController:update' => ['privates', '.service_locator.0dP2eJy.App\\Controller\\StudentController::update()', 'getStudentControllerupdateService', true],
            'App\\Controller\\StudentController:delete' => ['privates', '.service_locator.0dP2eJy.App\\Controller\\StudentController::delete()', 'getStudentControllerdeleteService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\CompanyController::index' => '?',
            'App\\Controller\\CompanyController::update' => '?',
            'App\\Controller\\JobController::index' => '?',
            'App\\Controller\\JobController::update' => '?',
            'App\\Controller\\SchoolController::index' => '?',
            'App\\Controller\\SchoolController::update' => '?',
            'App\\Controller\\StudentController::index' => '?',
            'App\\Controller\\StudentController::create' => '?',
            'App\\Controller\\StudentController::update' => '?',
            'App\\Controller\\StudentController::delete' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\CompanyController:index' => '?',
            'App\\Controller\\CompanyController:update' => '?',
            'App\\Controller\\JobController:index' => '?',
            'App\\Controller\\JobController:update' => '?',
            'App\\Controller\\SchoolController:index' => '?',
            'App\\Controller\\SchoolController:update' => '?',
            'App\\Controller\\StudentController:index' => '?',
            'App\\Controller\\StudentController:create' => '?',
            'App\\Controller\\StudentController:update' => '?',
            'App\\Controller\\StudentController:delete' => '?',
        ]);
    }
}
