<?php

namespace ContainerUximk1T;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSerializeControllerResultListenerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'serialize_controller_result_listener' shared service.
     *
     * @return \Symfony\Component\HttpKernel\EventListener\SerializeControllerResultAttributeListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'http-kernel'.\DIRECTORY_SEPARATOR.'EventListener'.\DIRECTORY_SEPARATOR.'SerializeControllerResultAttributeListener.php';

        return $container->privates['serialize_controller_result_listener'] = new \Symfony\Component\HttpKernel\EventListener\SerializeControllerResultAttributeListener(($container->privates['serializer'] ?? self::getSerializerService($container)));
    }
}
