<?php

namespace ContainerJr2UNQr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getJobControllercreateService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.xkvNjp6.App\Controller\JobController::create()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.xkvNjp6.App\\Controller\\JobController::create()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'aiEnrichmentService' => ['privates', 'App\\Service\\AiEnrichmentService', 'getAiEnrichmentServiceService', true],
        ], [
            'em' => '?',
            'aiEnrichmentService' => 'App\\Service\\AiEnrichmentService',
        ]))->withContext('App\\Controller\\JobController::create()', $container);
    }
}
