<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJr2UNQr\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJr2UNQr/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJr2UNQr.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJr2UNQr\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJr2UNQr\App_KernelDevDebugContainer([
    'container.build_hash' => 'Jr2UNQr',
    'container.build_id' => 'd6fdcee5',
    'container.build_time' => 1780472867,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJr2UNQr');
