<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBdaOktk\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBdaOktk/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBdaOktk.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerBdaOktk\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerBdaOktk\App_KernelDevDebugContainer([
    'container.build_hash' => 'BdaOktk',
    'container.build_id' => '82723bab',
    'container.build_time' => 1780348238,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBdaOktk');
