<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZLJy6dA\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZLJy6dA/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZLJy6dA.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZLJy6dA\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZLJy6dA\App_KernelDevDebugContainer([
    'container.build_hash' => 'ZLJy6dA',
    'container.build_id' => '8ad2580d',
    'container.build_time' => 1780434482,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZLJy6dA');
